# Application Name & Port
spring.application.name=StoryVoice
server.port=8080

# Disable Docker Compose auto-start (compose.yaml moved to backend/ folder)
spring.docker.compose.enabled=false


# Database Connection (MySQL)
spring.datasource.url=jdbc:mysql://localhost:3306/story_voice?useSSL=false&serverTimezone=UTC&allowPublicKeyRetrieval=true&createDatabaseIfNotExist=true
spring.datasource.username=root
spring.datasource.password=123456
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA / Hibernate Configurations
spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.format_sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.MySQLDialect

# File Upload Configurations
spring.servlet.multipart.max-file-size=50MB
spring.servlet.multipart.max-request-size=50MB
app.upload.dir=./uploads

# JWT Security Configurations
# Secret key
app.jwt.secret=StoryVoiceSecretKeyForJWTAuthentication2026SecureKeyWithMin256BitsLength!
app.jwt.expiration-ms=86400000

# Text-To-Speech (ElevenLabs API) Configurations
app.tts.elevenlabs.api-key=sk_8dff898dfebb92ca9fcec0b6a16a2b842375962b78aa1bc4
app.tts.elevenlabs.voice-id=cgSgspJ2msm6clMCkdW9
#app.tts.elevenlabs.voice-id=Jah7gy9AdShldcj4Vl1B
# app.tts.elevenlabs.voice-id=ehjy2c1Wl03Sf3q6R7UY
app.tts.elevenlabs.model-id=eleven_multilingual_v2

# Swagger / OpenAPI UI
springdoc.api-docs.path=/api-docs
springdoc.swagger-ui.path=/swagger-ui.html

# Google OAuth2 Configurations
spring.security.oauth2.client.registration.google.client-id=191758600715-6chb0785tbeduim7ajggfg5o3p8hsjqr.apps.googleusercontent.com
spring.security.oauth2.client.registration.google.client-secret=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
spring.security.oauth2.client.registration.google.scope=email,profile
# Frontend Google client-id
app.google.client-id=191758600715-6chb0785tbeduim7ajggfg5o3p8hsjqr.apps.googleusercontent.com
# URL Frontend sau khi login Google redirect
app.oauth2.authorized-redirect-uris=http://localhost:5173/oauth2/redirect

# SMTP Configuration
spring.mail.host=smtp.gmail.com
spring.mail.port=587
spring.mail.username=dcroinhe@gmail.com
spring.mail.password=epnp tmjg xdww blkn
spring.mail.properties.mail.smtp.auth=true
spring.mail.properties.mail.smtp.starttls.enable=true

# Cloudinary Configuration
cloudinary.cloud-name=dzrtrxxqk
cloudinary.api-key=972746964218182
cloudinary.api-secret=NKDcvE7Qc3KVD_B127dp8rpIQiA
